name: Deploy to GitHub Pages

on:
    push:
        branches:
            - build

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node
              uses: actions/setup-node@v2

            - name: Get version
              id: version
              run: |
                  echo ::set-output name=version::$(grep version package.json | sed 's|.*: \"\(.*\)\",|\1|')

            - run: yarn install
              env:
                  VERSION: ${{ steps.version.outputs.version }}
            - run: yarn build
              env:
                  VERSION: ${{ steps.version.outputs.version }}
            - run: cp config.json webapp/
            - run: |
                echo ${{ steps.version.outputs.version }} > webapp/version

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: webapp
                  fqdn: element.boba.best
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
